version: 2.1
orbs:
  node: circleci/node@5.1.0
  heroku: circleci/heroku@2.0.0

jobs:
  build_and_test: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install
          name: install
workflows:
  test_my_app:
    jobs:
      - build_and_test
